'use strict';
const canvas=document.getElementById('scene'),gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});
if(!gl) document.getElementById('status').textContent='此裝置無法顯示 WebGL；可下載 Rhino 底稿。';
const vertex=`attribute vec3 position;attribute vec3 normal;attribute vec3 color;uniform vec3 center;uniform vec2 angle;uniform float scale;uniform float aspect;uniform float perspective;uniform float cameraDistance;varying vec3 vN;varying vec3 vC;varying vec3 vP;vec3 rotate(vec3 p){float c=cos(angle.x),s=sin(angle.x);vec3 q=vec3(c*p.x+s*p.z,p.y,-s*p.x+c*p.z);c=cos(angle.y);s=sin(angle.y);return vec3(q.x,c*q.y-s*q.z,s*q.y+c*q.z);}void main(){vec3 p=rotate(position-center);vP=p;vN=rotate(normal);vC=color;gl_Position=vec4(p.x*scale/aspect,p.y*scale,-p.z/2000.,mix(1.,max(.1,1.-p.z/cameraDistance),perspective));}`;
const fragment=`precision highp float;varying vec3 vN;varying vec3 vC;varying vec3 vP;uniform float clay;uniform vec3 lightDirection;uniform float exposure;void main(){vec3 n=normalize(vN);if(!gl_FrontFacing)n=-n;vec3 l=normalize(lightDirection);float d=max(dot(n,l),0.);float rim=pow(max(0.,1.-abs(n.z)),2.);vec3 base=mix(vC,vec3(.69,.70,.69),clay);float spec=pow(max(0.,dot(n,normalize(l+vec3(0.,0.,1.)))),45.);vec3 c=base*(.48+.50*d)+vec3(.12)*spec+vec3(.04)*rim;gl_FragColor=vec4(c*exposure,1.);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);gl.useProgram(program);
let yaw=0,pitch=0,zoom=1,center=[515,-601,0],height=1160,vertexCount=0;
const locations={};['center','angle','scale','aspect','clay','perspective','cameraDistance','lightDirection','exposure'].forEach(k=>locations[k]=gl.getUniformLocation(program,k));
function normal(a,b,c){const u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]);const n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n)||1;return n.map(v=>v/l);}
fetch('geometry.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(meshes=>{const data=[];let strings=new Set(),keys=0;for(const m of meshes){if(m.name.startsWith('弦_'))strings.add(m.name.split('_')[1]);if(m.name.startsWith('細圓柱KEY'))keys++;for(const f of m.faces){const pts=f.map(i=>m.vertices[i]),n=normal(...pts);for(const p of pts)data.push(...p,...n,...m.color.map(c=>c/255));}}vertexCount=data.length/9;gl.bindBuffer(gl.ARRAY_BUFFER,gl.createBuffer());gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);['position','normal','color'].forEach((name,i)=>{const a=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,36,i*12);});document.getElementById('status').textContent=`模型已載入：${strings.size} 條弦、${keys} 顆圓柱 KEY。`;draw();}).catch(e=>document.getElementById('status').textContent='模型載入錯誤：'+e.message);
function draw(){const r=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.964,.96,.944,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.uniform3fv(locations.center,center);gl.uniform2f(locations.angle,yaw,pitch);gl.uniform1f(locations.scale,2*zoom/height);gl.uniform1f(locations.aspect,canvas.width/canvas.height);gl.uniform1f(locations.clay,document.getElementById('clay').checked?1:0);const fov=Number(document.getElementById('projection').value);gl.uniform1f(locations.perspective,fov?1:0);gl.uniform1f(locations.cameraDistance,fov?height/(2*zoom*Math.tan(fov*Math.PI/360)):1e6);gl.uniform3fv(locations.lightDirection,LIGHTS[document.getElementById('light').value]);gl.uniform1f(locations.exposure,Number(document.getElementById('exposure').value));gl.drawArrays(gl.TRIANGLES,0,vertexCount);drawMarks();}

const LIGHTS={soft:[-.7,.8,1.1],side:[-1.8,.3,.45],top:[.1,1.8,.5],back:[1.5,.8,-.5]};
const overlay=document.getElementById('marks'),pen=overlay.getContext('2d'),note=document.getElementById('review-note');
let strokes=[],stroke=null,marking=false,revision=null,records=[];
const views={front:{center:[515,-601,0],height:1160,yaw:0,pitch:0},fold:{center:[515,-860,-10],height:600,yaw:-.46,pitch:.14},side:{center:[515,-601,0],height:1160,yaw:-1.22,pitch:.12},head:{center:[515,-187,4],height:242,yaw:0,pitch:0},hardware:{center:[515,-919,2],height:390,yaw:0,pitch:0},pickups:{center:[515,-830,4],height:185,yaw:0,pitch:0},bridge:{center:[515,-935,10],height:62,yaw:-.18,pitch:.55},joint:{center:[516,-250,2],height:112,yaw:-1.4,pitch:0}};
function selectView(id){const v=views[id];if(!v)return;({yaw,pitch,height}=v);center=[...v.center];zoom=1;strokes=[];setMarking(false);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));draw();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view));
function drawMarks(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);overlay.width=Math.round(r.width*d);overlay.height=Math.round(r.height*d);pen.setTransform(d,0,0,d,0,0);pen.clearRect(0,0,r.width,r.height);pen.strokeStyle='#da302d';pen.lineWidth=3;pen.lineCap='round';pen.lineJoin='round';for(const points of strokes){pen.beginPath();points.forEach(([x,y],i)=>{const px=r.width/2+x*r.height,py=r.height/2+y*r.height;i?pen.lineTo(px,py):pen.moveTo(px,py);});pen.stroke();}}
function setMarking(value){marking=value;overlay.style.pointerEvents=value?'auto':'none';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',(b.dataset.mode==='mark')===value));}
document.querySelector('[data-mode="mark"]').onclick=()=>setMarking(true);
document.querySelector('[data-mode="rotate"]').onclick=()=>setMarking(false);
document.getElementById('clear-marks').onclick=()=>{strokes=[];drawMarks();};
function point(e){const r=overlay.getBoundingClientRect();return [(e.clientX-r.left-r.width/2)/r.height,(e.clientY-r.top-r.height/2)/r.height];}
overlay.onpointerdown=e=>{stroke=[point(e)];strokes.push(stroke);overlay.setPointerCapture(e.pointerId);drawMarks();};
overlay.onpointermove=e=>{if(stroke&&stroke.length<3000){stroke.push(point(e));drawMarks();}};
overlay.onpointerup=overlay.onpointercancel=()=>stroke=null;
let drag=null;
canvas.onpointerdown=e=>{if(marking)return;drag=[e.clientX,e.clientY,yaw,pitch];canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!drag)return;strokes=[];yaw=drag[2]+(e.clientX-drag[0])*.006;pitch=drag[3]+(e.clientY-drag[1])*.006;draw();};
canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
canvas.onwheel=e=>{if(marking)return;e.preventDefault();strokes=[];zoom=Math.max(.5,Math.min(7,zoom*Math.exp(-e.deltaY*.001)));draw();};
for(const id of ['clay','light','exposure','projection'])document.getElementById(id).oninput=draw;
new ResizeObserver(()=>{draw();drawMarks();}).observe(canvas);
function camera(){return {yaw,pitch,zoom,center:[...center],height,projection:Number(document.getElementById('projection').value),light:document.getElementById('light').value,exposure:Number(document.getElementById('exposure').value),clay:document.getElementById('clay').checked};}
function imageData(){draw();const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height+112;const c=out.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,out.width,out.height);c.drawImage(canvas,0,0);c.drawImage(overlay,0,0,canvas.width,canvas.height);c.fillStyle='#222';c.font='20px sans-serif';c.fillText('QAF1 · '+(revision?.updated_at||'')+' · '+document.getElementById('projection').selectedOptions[0].text,24,canvas.height+30);const text=note.value.trim();c.font='18px sans-serif';let line='',y=canvas.height+60;for(const ch of text.slice(0,260)){if(c.measureText(line+ch).width>out.width-48){c.fillText(line,24,y);line='';y+=25;}line+=ch;}c.fillText(line,24,y);return out.toDataURL('image/png');}
document.getElementById('download-review').onclick=()=>{const a=document.createElement('a');a.href=imageData();a.download='QAF1-模型溝通-'+new Date().toISOString().slice(0,10)+'.png';a.click();};
const token=document.querySelector('meta[name="qaf1-token"]').content;
async function reviews(){if(token.startsWith('__'))return;try{const r=await fetch('/api/qaf1-model/reviews',{cache:'no-store'});if(!r.ok)throw Error('讀取失敗');records=await r.json();const list=document.getElementById('review-list');list.replaceChildren();for(const record of records){const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.textContent=record.created_at.slice(0,16).replace('T',' ')+' · '+(record.note||'圈選標註').slice(0,55);b.onclick=()=>restore(record);li.append(b);list.append(li);}document.getElementById('review-count').textContent=records.length?'已保存 '+records.length+' 則':'尚未保存標註';}catch(e){document.getElementById('review-count').textContent='標註清單暫時無法讀取';}}
function restore(record){const s=record.camera;({yaw,pitch,zoom,height}=s);center=[...s.center];for(const k of ['light','projection','exposure'])document.getElementById(k).value=s[k];document.getElementById('clay').checked=s.clay;strokes=record.strokes;note.value=record.note;setMarking(true);draw();document.getElementById('review-status').textContent='已還原保存時的視角、光源和標記。';}
document.getElementById('save-review').onclick=async()=>{const b=document.getElementById('save-review'),status=document.getElementById('review-status');if(token.startsWith('__')){status.textContent='請從主站 QAF1 儲存討論；此頁仍可下載標註圖。';return;}if(!note.value.trim()&&!strokes.length){status.textContent='請先圈選位置或寫下修改內容。';return;}b.disabled=true;status.textContent='儲存中…';try{const r=await fetch('/api/qaf1-model/reviews',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':token},body:JSON.stringify({note:note.value,camera:camera(),strokes,image:imageData()})});const result=await r.json();if(!r.ok)throw Error(result.error||'儲存失敗');status.textContent='已儲存，可從下方清單重新開啟。';await reviews();}catch(e){status.textContent=e.message;}finally{b.disabled=false;}};
fetch('revision.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(r=>{revision=r;document.getElementById('revision').textContent='模型更新：'+r.updated_at.replace('T',' ').slice(0,19);});
const params=new URLSearchParams(location.search);if(params.has('embedded'))document.documentElement.classList.add('embedded');selectView(params.get('view')||'front');reviews();
